"""initial vyron schema

Revision ID: 614fd1cdb953
Revises: 
Create Date: 2026-09-12 05:32:18.889635+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import vyron.db.base  # noqa: F401 — custom types


revision: str = '614fd1cdb953'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('games',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('accent_color', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('required_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_slug'), 'games', ['slug'], unique=True)
    op.create_index(op.f('ix_games_sort_order'), 'games', ['sort_order'], unique=False)
    op.create_index(op.f('ix_games_status'), 'games', ['status'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('key_value', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('expires_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'key_value', name='uq_idempotency_scope_key')
    )
    op.create_index(op.f('ix_idempotency_keys_expires_at'), 'idempotency_keys', ['expires_at'], unique=False)
    op.create_table('order_sequences',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('platform_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('promotions',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('badge_text', sa.String(length=60), nullable=True),
    sa.Column('starts_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('ends_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_active'), 'promotions', ['active'], unique=False)
    op.create_index(op.f('ix_promotions_slug'), 'promotions', ['slug'], unique=True)
    op.create_table('seller_subscription_plans',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('suppliers',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('provider_kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('encrypted_config', sa.Text(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('balance_currency', sa.String(length=8), nullable=False),
    sa.Column('balance_checked_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('last_sync_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('success_rate_30d', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_priority'), 'suppliers', ['priority'], unique=False)
    op.create_index(op.f('ix_suppliers_slug'), 'suppliers', ['slug'], unique=True)
    op.create_index(op.f('ix_suppliers_status'), 'suppliers', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('fraud_risk_score', sa.Integer(), nullable=False),
    sa.Column('last_login_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('admin_actions',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('admin_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=400), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_actions_action'), 'admin_actions', ['action'], unique=False)
    op.create_index(op.f('ix_admin_actions_admin_id'), 'admin_actions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_actions_created_at'), 'admin_actions', ['created_at'], unique=False)
    op.create_table('carts',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('coupon_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=True)
    op.create_table('coupons',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('per_user_limit', sa.Integer(), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('product_ids', sa.JSON(), nullable=True),
    sa.Column('game_ids', sa.JSON(), nullable=True),
    sa.Column('user_ids', sa.JSON(), nullable=True),
    sa.Column('starts_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('expires_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_active'), 'coupons', ['active'], unique=False)
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_index(op.f('ix_coupons_expires_at'), 'coupons', ['expires_at'], unique=False)
    op.create_table('donation_pages',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_pages_active'), 'donation_pages', ['active'], unique=False)
    op.create_index(op.f('ix_donation_pages_user_id'), 'donation_pages', ['user_id'], unique=True)
    op.create_table('email_outbox',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=140), nullable=True),
    sa.Column('sent_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_email_outbox_created_at'), 'email_outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_outbox_status'), 'email_outbox', ['status'], unique=False)
    op.create_index(op.f('ix_email_outbox_to_email'), 'email_outbox', ['to_email'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('user_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=60), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_created_at'), 'login_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_index('ix_login_attempts_ip_created', 'login_attempts', ['ip_address', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('link', sa.String(length=400), nullable=True),
    sa.Column('read_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_read_at'), 'notifications', ['read_at'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('used_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('game_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('required_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_active'), 'products', ['active'], unique=False)
    op.create_index('ix_products_game_active_sort', 'products', ['game_id', 'active', 'sort_order'], unique=False)
    op.create_index(op.f('ix_products_game_id'), 'products', ['game_id'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_index(op.f('ix_products_type'), 'products', ['type'], unique=False)
    op.create_table('seller_profiles',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('completed_orders', sa.Integer(), nullable=False),
    sa.Column('cancelled_orders', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('commission_override_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_profiles_status'), 'seller_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_seller_profiles_user_id'), 'seller_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_seller_profiles_verification_status'), 'seller_profiles', ['verification_status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('revoked_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('telegram_connections',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('linked_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_connections_telegram_id'), 'telegram_connections', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_telegram_connections_user_id'), 'telegram_connections', ['user_id'], unique=True)
    op.create_table('telegram_link_tokens',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('used_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_link_tokens_expires_at'), 'telegram_link_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_telegram_link_tokens_token_hash'), 'telegram_link_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_telegram_link_tokens_user_id'), 'telegram_link_tokens', ['user_id'], unique=False)
    op.create_table('verification_tokens',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('expires_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('used_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_tokens_expires_at'), 'verification_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_verification_tokens_token_hash'), 'verification_tokens', ['token_hash'], unique=True)
    op.create_index('ix_verification_tokens_user_purpose', 'verification_tokens', ['user_id', 'purpose'], unique=False)
    op.create_table('orders',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('number', sa.String(length=24), nullable=False),
    sa.Column('user_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('service_fee', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('supplier_cost_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('coupon_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('payment_provider', sa.String(length=24), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=12), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('customer_note', sa.String(length=500), nullable=True),
    sa.Column('paid_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('completed_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('cancelled_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_orders_completed_at'), 'orders', ['completed_at'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_number'), 'orders', ['number'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index('ix_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index('ix_orders_user_created', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_table('payout_requests',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('seller_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('details_enc', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by_user_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('review_note', sa.String(length=400), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('processed_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_payout_requests_created_at'), 'payout_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_payout_requests_seller_id'), 'payout_requests', ['seller_id'], unique=False)
    op.create_index(op.f('ix_payout_requests_status'), 'payout_requests', ['status'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('product_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('external_product_id', sa.String(length=120), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'name', name='uq_variant_product_name')
    )
    op.create_index(op.f('ix_product_variants_active'), 'product_variants', ['active'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index('ix_variant_external', 'product_variants', ['external_product_id'], unique=False)
    op.create_table('seller_balance_transactions',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('seller_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('pending_delta', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('available_delta', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('reserved_delta', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=140), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('available_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_seller_balance_tx_idempotency')
    )
    op.create_index(op.f('ix_seller_balance_transactions_available_at'), 'seller_balance_transactions', ['available_at'], unique=False)
    op.create_index(op.f('ix_seller_balance_transactions_created_at'), 'seller_balance_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_seller_balance_transactions_seller_id'), 'seller_balance_transactions', ['seller_id'], unique=False)
    op.create_index(op.f('ix_seller_balance_transactions_type'), 'seller_balance_transactions', ['type'], unique=False)
    op.create_table('seller_balances',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('seller_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('pending', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('available', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('reserved', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('lifetime_earnings', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('lifetime_paid', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_balances_seller_id'), 'seller_balances', ['seller_id'], unique=True)
    op.create_table('seller_listings',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('seller_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('game_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('delivery_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('sensitive_delivery_data_enc', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=400), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('is_promoted', sa.Boolean(), nullable=False),
    sa.Column('approved_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listings_status_created', 'seller_listings', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_seller_listings_created_at'), 'seller_listings', ['created_at'], unique=False)
    op.create_index(op.f('ix_seller_listings_game_id'), 'seller_listings', ['game_id'], unique=False)
    op.create_index(op.f('ix_seller_listings_is_promoted'), 'seller_listings', ['is_promoted'], unique=False)
    op.create_index(op.f('ix_seller_listings_seller_id'), 'seller_listings', ['seller_id'], unique=False)
    op.create_index(op.f('ix_seller_listings_status'), 'seller_listings', ['status'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('cart_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('variant_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('required_field_values', sa.JSON(), nullable=True),
    sa.Column('values_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'variant_id', 'values_hash', name='uq_cart_item_variant_values')
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_variant_id'), 'cart_items', ['variant_id'], unique=False)
    op.create_table('coupon_redemptions',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('coupon_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('order_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('discount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coupon_id', 'order_id', name='uq_redemption_coupon_order')
    )
    op.create_index(op.f('ix_coupon_redemptions_coupon_id'), 'coupon_redemptions', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_redemptions_user_id'), 'coupon_redemptions', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('order_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('variant_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('variant_name', sa.String(length=160), nullable=False),
    sa.Column('game_name', sa.String(length=140), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('required_field_values', sa.JSON(), nullable=True),
    sa.Column('delivery_state', sa.String(length=24), nullable=False),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_delivery_state'), 'order_items', ['delivery_state'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('order_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=24), nullable=True),
    sa.Column('to_status', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=400), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('order_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('donation_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('seller_order_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('listing_promotion_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('seller_subscription_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('user_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=190), nullable=True),
    sa.Column('status', sa.String(length=28), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('processing_fee', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('refunded_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('checkout_url', sa.String(length=1000), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('paid_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('expires_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('provider', 'provider_payment_id', name='uq_payment_provider_reference')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_donation_id'), 'payments', ['donation_id'], unique=False)
    op.create_index(op.f('ix_payments_listing_promotion_id'), 'payments', ['listing_promotion_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_paid_at'), 'payments', ['paid_at'], unique=False)
    op.create_index(op.f('ix_payments_provider'), 'payments', ['provider'], unique=False)
    op.create_index(op.f('ix_payments_purpose'), 'payments', ['purpose'], unique=False)
    op.create_index(op.f('ix_payments_seller_order_id'), 'payments', ['seller_order_id'], unique=False)
    op.create_index(op.f('ix_payments_seller_subscription_id'), 'payments', ['seller_subscription_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index('ix_payments_status_created', 'payments', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('supplier_products',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('supplier_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('variant_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('external_product_id', sa.String(length=120), nullable=False),
    sa.Column('supplier_cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'variant_id', name='uq_supplier_variant')
    )
    op.create_index('ix_supplier_product_variant_active', 'supplier_products', ['variant_id', 'available'], unique=False)
    op.create_index(op.f('ix_supplier_products_supplier_id'), 'supplier_products', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_products_variant_id'), 'supplier_products', ['variant_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('user_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('order_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=12), nullable=False),
    sa.Column('assigned_to', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('last_message_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_created_at'), 'support_tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_tickets_last_message_at'), 'support_tickets', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_support_tickets_number'), 'support_tickets', ['number'], unique=True)
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('donations',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('page_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('payment_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('donor_user_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('donor_name', sa.String(length=120), nullable=True),
    sa.Column('donor_email', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('completed_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['donor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['donation_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_donations_created_at'), 'donations', ['created_at'], unique=False)
    op.create_index(op.f('ix_donations_donor_user_id'), 'donations', ['donor_user_id'], unique=False)
    op.create_index('ix_donations_page_created', 'donations', ['page_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_donations_page_id'), 'donations', ['page_id'], unique=False)
    op.create_index(op.f('ix_donations_payment_id'), 'donations', ['payment_id'], unique=False)
    op.create_index(op.f('ix_donations_status'), 'donations', ['status'], unique=False)
    op.create_table('fraud_events',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('order_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('payment_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('type', sa.String(length=28), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.String(length=300), nullable=True),
    sa.Column('resolved_by', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('resolved_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_events_created_at'), 'fraud_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_fraud_events_level'), 'fraud_events', ['level'], unique=False)
    op.create_index(op.f('ix_fraud_events_resolved'), 'fraud_events', ['resolved'], unique=False)
    op.create_index(op.f('ix_fraud_events_type'), 'fraud_events', ['type'], unique=False)
    op.create_index(op.f('ix_fraud_events_user_id'), 'fraud_events', ['user_id'], unique=False)
    op.create_index('ix_fraud_user_created', 'fraud_events', ['user_id', 'created_at'], unique=False)
    op.create_table('listing_promotions',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('listing_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('seller_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('payment_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('starts_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('ends_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['seller_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_promotions_ends_at'), 'listing_promotions', ['ends_at'], unique=False)
    op.create_index(op.f('ix_listing_promotions_listing_id'), 'listing_promotions', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_promotions_seller_id'), 'listing_promotions', ['seller_id'], unique=False)
    op.create_index(op.f('ix_listing_promotions_status'), 'listing_promotions', ['status'], unique=False)
    op.create_table('payment_webhooks',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('event_id', sa.String(length=190), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=True),
    sa.Column('payment_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('received_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('processed_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_webhook_provider_event')
    )
    op.create_index(op.f('ix_payment_webhooks_event_id'), 'payment_webhooks', ['event_id'], unique=False)
    op.create_index(op.f('ix_payment_webhooks_processed'), 'payment_webhooks', ['processed'], unique=False)
    op.create_index(op.f('ix_payment_webhooks_provider'), 'payment_webhooks', ['provider'], unique=False)
    op.create_index(op.f('ix_payment_webhooks_received_at'), 'payment_webhooks', ['received_at'], unique=False)
    op.create_table('refunds',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('payment_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('order_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_refund_id', sa.String(length=190), nullable=True),
    sa.Column('requested_by_user_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('processed_by_user_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_refunds_created_at'), 'refunds', ['created_at'], unique=False)
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_index(op.f('ix_refunds_status'), 'refunds', ['status'], unique=False)
    op.create_table('seller_orders',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('number', sa.String(length=24), nullable=False),
    sa.Column('listing_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('seller_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('buyer_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('payment_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('commission_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('seller_earning', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('delivery_note', sa.Text(), nullable=True),
    sa.Column('delivered_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('completed_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['listing_id'], ['seller_listings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_seller_orders_buyer_id'), 'seller_orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_seller_orders_completed_at'), 'seller_orders', ['completed_at'], unique=False)
    op.create_index(op.f('ix_seller_orders_created_at'), 'seller_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_seller_orders_listing_id'), 'seller_orders', ['listing_id'], unique=False)
    op.create_index(op.f('ix_seller_orders_number'), 'seller_orders', ['number'], unique=True)
    op.create_index(op.f('ix_seller_orders_payment_id'), 'seller_orders', ['payment_id'], unique=False)
    op.create_index('ix_seller_orders_seller_created', 'seller_orders', ['seller_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_seller_orders_seller_id'), 'seller_orders', ['seller_id'], unique=False)
    op.create_index(op.f('ix_seller_orders_status'), 'seller_orders', ['status'], unique=False)
    op.create_table('seller_subscriptions',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('seller_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('plan_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('payment_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('starts_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('ends_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['seller_subscription_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_subscriptions_ends_at'), 'seller_subscriptions', ['ends_at'], unique=False)
    op.create_index(op.f('ix_seller_subscriptions_seller_id'), 'seller_subscriptions', ['seller_id'], unique=False)
    op.create_index(op.f('ix_seller_subscriptions_status'), 'seller_subscriptions', ['status'], unique=False)
    op.create_table('supplier_orders',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('order_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('order_item_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('supplier_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('external_order_id', sa.String(length=190), nullable=True),
    sa.Column('idempotency_key', sa.String(length=140), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('recipient_payload', sa.JSON(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('submitted_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('completed_at', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('reconcile_after', vyron.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_supplier_order_idempotency')
    )
    op.create_index(op.f('ix_supplier_orders_external_order_id'), 'supplier_orders', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_supplier_orders_order_id'), 'supplier_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_supplier_orders_order_item_id'), 'supplier_orders', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_supplier_orders_reconcile_after'), 'supplier_orders', ['reconcile_after'], unique=False)
    op.create_index(op.f('ix_supplier_orders_status'), 'supplier_orders', ['status'], unique=False)
    op.create_index('ix_supplier_orders_status_reconcile', 'supplier_orders', ['status', 'reconcile_after'], unique=False)
    op.create_index(op.f('ix_supplier_orders_supplier_id'), 'supplier_orders', ['supplier_id'], unique=False)
    op.create_table('support_messages',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('ticket_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('author_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('author_role', sa.String(length=20), nullable=False),
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_messages_created_at'), 'support_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_messages_ticket_id'), 'support_messages', ['ticket_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('payment_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('order_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('user_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('seller_profile_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('payout_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('idempotency_key', sa.String(length=140), nullable=False),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payout_id'], ['payout_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_profile_id'], ['seller_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_transaction_idempotency')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_payment_id'), 'transactions', ['payment_id'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_index('ix_transactions_type_created', 'transactions', ['type', 'created_at'], unique=False)
    op.create_table('donation_transactions',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('donation_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('payment_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('recipient_user_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('donor_user_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['donor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('donation_id', name='uq_donation_tx_donation')
    )
    op.create_index(op.f('ix_donation_transactions_created_at'), 'donation_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_donation_transactions_donation_id'), 'donation_transactions', ['donation_id'], unique=False)
    op.create_index(op.f('ix_donation_transactions_recipient_user_id'), 'donation_transactions', ['recipient_user_id'], unique=False)
    op.create_table('revenue_ledger',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('stream', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('order_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('payment_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('donation_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('seller_order_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('payout_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('product_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('game_id', vyron.db.base.GUID(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payout_id'], ['payout_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_order_id'], ['seller_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_revenue_ledger_idempotency')
    )
    op.create_index('ix_revenue_game_created', 'revenue_ledger', ['game_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_revenue_ledger_created_at'), 'revenue_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_revenue_ledger_stream'), 'revenue_ledger', ['stream'], unique=False)
    op.create_index('ix_revenue_stream_created', 'revenue_ledger', ['stream', 'created_at'], unique=False)
    op.create_table('supplier_order_attempts',
    sa.Column('id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('supplier_order_id', vyron.db.base.GUID(length=36), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('request_ref', sa.String(length=190), nullable=True),
    sa.Column('response_excerpt', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', vyron.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_order_id'], ['supplier_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_order_attempts_supplier_order_id'), 'supplier_order_attempts', ['supplier_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_order_attempts_supplier_order_id'), table_name='supplier_order_attempts')
    op.drop_table('supplier_order_attempts')
    op.drop_index('ix_revenue_stream_created', table_name='revenue_ledger')
    op.drop_index(op.f('ix_revenue_ledger_stream'), table_name='revenue_ledger')
    op.drop_index(op.f('ix_revenue_ledger_created_at'), table_name='revenue_ledger')
    op.drop_index('ix_revenue_game_created', table_name='revenue_ledger')
    op.drop_table('revenue_ledger')
    op.drop_index(op.f('ix_donation_transactions_recipient_user_id'), table_name='donation_transactions')
    op.drop_index(op.f('ix_donation_transactions_donation_id'), table_name='donation_transactions')
    op.drop_index(op.f('ix_donation_transactions_created_at'), table_name='donation_transactions')
    op.drop_table('donation_transactions')
    op.drop_index('ix_transactions_type_created', table_name='transactions')
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payment_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_support_messages_ticket_id'), table_name='support_messages')
    op.drop_index(op.f('ix_support_messages_created_at'), table_name='support_messages')
    op.drop_table('support_messages')
    op.drop_index(op.f('ix_supplier_orders_supplier_id'), table_name='supplier_orders')
    op.drop_index('ix_supplier_orders_status_reconcile', table_name='supplier_orders')
    op.drop_index(op.f('ix_supplier_orders_status'), table_name='supplier_orders')
    op.drop_index(op.f('ix_supplier_orders_reconcile_after'), table_name='supplier_orders')
    op.drop_index(op.f('ix_supplier_orders_order_item_id'), table_name='supplier_orders')
    op.drop_index(op.f('ix_supplier_orders_order_id'), table_name='supplier_orders')
    op.drop_index(op.f('ix_supplier_orders_external_order_id'), table_name='supplier_orders')
    op.drop_table('supplier_orders')
    op.drop_index(op.f('ix_seller_subscriptions_status'), table_name='seller_subscriptions')
    op.drop_index(op.f('ix_seller_subscriptions_seller_id'), table_name='seller_subscriptions')
    op.drop_index(op.f('ix_seller_subscriptions_ends_at'), table_name='seller_subscriptions')
    op.drop_table('seller_subscriptions')
    op.drop_index(op.f('ix_seller_orders_status'), table_name='seller_orders')
    op.drop_index(op.f('ix_seller_orders_seller_id'), table_name='seller_orders')
    op.drop_index('ix_seller_orders_seller_created', table_name='seller_orders')
    op.drop_index(op.f('ix_seller_orders_payment_id'), table_name='seller_orders')
    op.drop_index(op.f('ix_seller_orders_number'), table_name='seller_orders')
    op.drop_index(op.f('ix_seller_orders_listing_id'), table_name='seller_orders')
    op.drop_index(op.f('ix_seller_orders_created_at'), table_name='seller_orders')
    op.drop_index(op.f('ix_seller_orders_completed_at'), table_name='seller_orders')
    op.drop_index(op.f('ix_seller_orders_buyer_id'), table_name='seller_orders')
    op.drop_table('seller_orders')
    op.drop_index(op.f('ix_refunds_status'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_created_at'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_payment_webhooks_received_at'), table_name='payment_webhooks')
    op.drop_index(op.f('ix_payment_webhooks_provider'), table_name='payment_webhooks')
    op.drop_index(op.f('ix_payment_webhooks_processed'), table_name='payment_webhooks')
    op.drop_index(op.f('ix_payment_webhooks_event_id'), table_name='payment_webhooks')
    op.drop_table('payment_webhooks')
    op.drop_index(op.f('ix_listing_promotions_status'), table_name='listing_promotions')
    op.drop_index(op.f('ix_listing_promotions_seller_id'), table_name='listing_promotions')
    op.drop_index(op.f('ix_listing_promotions_listing_id'), table_name='listing_promotions')
    op.drop_index(op.f('ix_listing_promotions_ends_at'), table_name='listing_promotions')
    op.drop_table('listing_promotions')
    op.drop_index('ix_fraud_user_created', table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_user_id'), table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_type'), table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_resolved'), table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_level'), table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_created_at'), table_name='fraud_events')
    op.drop_table('fraud_events')
    op.drop_index(op.f('ix_donations_status'), table_name='donations')
    op.drop_index(op.f('ix_donations_payment_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_page_id'), table_name='donations')
    op.drop_index('ix_donations_page_created', table_name='donations')
    op.drop_index(op.f('ix_donations_donor_user_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_created_at'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_number'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_last_message_at'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_created_at'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_supplier_products_variant_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_supplier_id'), table_name='supplier_products')
    op.drop_index('ix_supplier_product_variant_active', table_name='supplier_products')
    op.drop_table('supplier_products')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index('ix_payments_status_created', table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_seller_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_seller_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_purpose'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider'), table_name='payments')
    op.drop_index(op.f('ix_payments_paid_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_listing_promotion_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_donation_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_delivery_state'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_coupon_redemptions_user_id'), table_name='coupon_redemptions')
    op.drop_index(op.f('ix_coupon_redemptions_coupon_id'), table_name='coupon_redemptions')
    op.drop_table('coupon_redemptions')
    op.drop_index(op.f('ix_cart_items_variant_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_seller_listings_status'), table_name='seller_listings')
    op.drop_index(op.f('ix_seller_listings_seller_id'), table_name='seller_listings')
    op.drop_index(op.f('ix_seller_listings_is_promoted'), table_name='seller_listings')
    op.drop_index(op.f('ix_seller_listings_game_id'), table_name='seller_listings')
    op.drop_index(op.f('ix_seller_listings_created_at'), table_name='seller_listings')
    op.drop_index('ix_listings_status_created', table_name='seller_listings')
    op.drop_table('seller_listings')
    op.drop_index(op.f('ix_seller_balances_seller_id'), table_name='seller_balances')
    op.drop_table('seller_balances')
    op.drop_index(op.f('ix_seller_balance_transactions_type'), table_name='seller_balance_transactions')
    op.drop_index(op.f('ix_seller_balance_transactions_seller_id'), table_name='seller_balance_transactions')
    op.drop_index(op.f('ix_seller_balance_transactions_created_at'), table_name='seller_balance_transactions')
    op.drop_index(op.f('ix_seller_balance_transactions_available_at'), table_name='seller_balance_transactions')
    op.drop_table('seller_balance_transactions')
    op.drop_index('ix_variant_external', table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_active'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_payout_requests_status'), table_name='payout_requests')
    op.drop_index(op.f('ix_payout_requests_seller_id'), table_name='payout_requests')
    op.drop_index(op.f('ix_payout_requests_created_at'), table_name='payout_requests')
    op.drop_table('payout_requests')
    op.drop_index('ix_orders_user_created', table_name='orders')
    op.drop_index('ix_orders_status_created', table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_completed_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_verification_tokens_user_purpose', table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_token_hash'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_expires_at'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('ix_telegram_link_tokens_user_id'), table_name='telegram_link_tokens')
    op.drop_index(op.f('ix_telegram_link_tokens_token_hash'), table_name='telegram_link_tokens')
    op.drop_index(op.f('ix_telegram_link_tokens_expires_at'), table_name='telegram_link_tokens')
    op.drop_table('telegram_link_tokens')
    op.drop_index(op.f('ix_telegram_connections_user_id'), table_name='telegram_connections')
    op.drop_index(op.f('ix_telegram_connections_telegram_id'), table_name='telegram_connections')
    op.drop_table('telegram_connections')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_seller_profiles_verification_status'), table_name='seller_profiles')
    op.drop_index(op.f('ix_seller_profiles_user_id'), table_name='seller_profiles')
    op.drop_index(op.f('ix_seller_profiles_status'), table_name='seller_profiles')
    op.drop_table('seller_profiles')
    op.drop_index(op.f('ix_products_type'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_game_id'), table_name='products')
    op.drop_index('ix_products_game_active_sort', table_name='products')
    op.drop_index(op.f('ix_products_active'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_login_attempts_ip_created', table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_created_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_email_outbox_to_email'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_status'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_created_at'), table_name='email_outbox')
    op.drop_table('email_outbox')
    op.drop_index(op.f('ix_donation_pages_user_id'), table_name='donation_pages')
    op.drop_index(op.f('ix_donation_pages_active'), table_name='donation_pages')
    op.drop_table('donation_pages')
    op.drop_index(op.f('ix_coupons_expires_at'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_active'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_admin_actions_created_at'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_admin_id'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_action'), table_name='admin_actions')
    op.drop_table('admin_actions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_status'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_slug'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_priority'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('seller_subscription_plans')
    op.drop_index(op.f('ix_promotions_slug'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_active'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_table('platform_settings')
    op.drop_table('order_sequences')
    op.drop_index(op.f('ix_idempotency_keys_expires_at'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_games_status'), table_name='games')
    op.drop_index(op.f('ix_games_sort_order'), table_name='games')
    op.drop_index(op.f('ix_games_slug'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
