"""Aggregate all SQLAlchemy models. Import models from here."""
from app.models.base import Base, TimestampMixin
from app.models.catalog import Game, GameCategory, Product, ProductVariant, Supplier, SupplierOrder, SupplierProduct
from app.models.commerce import (
    Coupon,
    CouponUsage,
    Order,
    OrderItem,
    OrderStatus,
    Payment,
    PaymentStatus,
    PaymentTransaction,
    Promotion,
    Refund,
    RevenueLedger,
    Wallet,
    WalletTransaction,
)
from app.models.donations import Donation, DonationProfile
from app.models.marketplace import (
    MarketplaceListing,
    PayoutStatus,
    Seller,
    SellerBalance,
    SellerPayout,
)
from app.models.support import (
    AuditLog,
    EmailVerificationToken,
    Favorite,
    MediaFile,
    Notification,
    PasswordResetToken,
    Review,
    Setting,
    SupportMessage,
    SupportTicket,
)
from app.models.users import Admin, TelegramUser, User, UserRole, UserSession

__all__ = [
    "Base",
    "TimestampMixin",
    "User",
    "UserRole",
    "UserSession",
    "TelegramUser",
    "Admin",
    "GameCategory",
    "Game",
    "Product",
    "ProductVariant",
    "Supplier",
    "SupplierProduct",
    "SupplierOrder",
    "Order",
    "OrderItem",
    "OrderStatus",
    "Payment",
    "PaymentStatus",
    "PaymentTransaction",
    "Refund",
    "Coupon",
    "CouponUsage",
    "Promotion",
    "Wallet",
    "WalletTransaction",
    "RevenueLedger",
    "Seller",
    "SellerBalance",
    "SellerPayout",
    "PayoutStatus",
    "MarketplaceListing",
    "DonationProfile",
    "Donation",
    "Notification",
    "SupportTicket",
    "SupportMessage",
    "Review",
    "Favorite",
    "AuditLog",
    "EmailVerificationToken",
    "Setting",
    "MediaFile",
    "PasswordResetToken",
]
